### PR TITLE
feat: download all episodes at once

### PR DESCRIPTION
**Pull request by EmanueleSpadaro**
now you can insert * as episode number to download all the available episodes for a given series season

### CODE REVIEW

**Comment by Arrowar** [comment]
Can you insert it, in another function / option in run.py ?

**Comment by EmanueleSpadaro** [comment]
Option as terminal parameter?  Furthermore, do you want me to do this or not? Given that you've closed the pull request for some reason

**Comment by Arrowar** [comment]
Yes, sorry i miss click, like after select the seson ask, do you want to download all the ep or a single one, if all do all if else, continue with what i write, just like that

**Comment by Arrowar** [comment]
This week i dont have to much time to code.

**Comment by EmanueleSpadaro** [comment]
Alright, I'll work on it

**Comment by Arrowar** [comment]
Perfect

**Comment by EmanueleSpadaro** [comment]
Perfect, now the code and user interaction are much cleaner

**Comment by Arrowar** [comment]
Perfect, change req.ok() in tv.py, because is a variable and not a function and add simple log([green]Name download ep: ep['name']) and i upload it.

**Comment by EmanueleSpadaro** [comment]
As of the latest commit, req.ok is already fixed.
Do you want me to switch
```python
console.print(f"[green]Ep: [blue]{ep['n']} [green]=> [purple]{ep['name']}")
```
to
```python
console.print(f"[green]Name download ep: ep['name']")
```
?

**Comment by Arrowar** [comment]
Only add a line that show ep name when download all with *

**Comment by Arrowar** [comment]
Today if I have time i will upload it, i prefer the insert with question in tv.py and not in run.py

**Pull request merged**
