### PR TITLE
create dockerization for the script

### PR DESCRIPTION
**Pull request by FrancescoGrazioso**
I'm trying to create a dockerization of the project, to make it easier to run it across different enviroments

### CODE REVIEW

**Comment by Arrowar** [comment]
Ok perfect, there is something else to add to make it work with linux ?

**Comment by FrancescoGrazioso** [comment]
> Ok perfect, there is something else to add to make it work with linux ?

still testing some things (some dependencies broke on the anime side), i'm testing in parallel an anime and series download, i'll put the PR in ready when i think i'll be done

**Comment by Arrowar** [comment]
Ok no problem, i know that take a lot of time if all work.

**Comment by FrancescoGrazioso** [comment]
> Ok no problem, i know that take a lot of time if all work.

no no it's actually already working pretty well, i took the liberty to edit the run.py file and let the user choose between anime and film at launch (this way you don't need to build the container every time you change the flag in `config.json`)

**Comment by Arrowar** [comment]
Yes I know, but for testing is easier with config but no problem. Maybe tqdm need to be fix, it use to much cpu, but is complicate to find the fix.

**Comment by FrancescoGrazioso** [comment]
> Yes I know, but for testing is easier with config but no problem. Maybe tqdm need to be fix, it use to much cpu, but is complicate to find the fix.

well it's graphically pleasant but (in my case) it will be run on a raspbarry where i host the plex server so yeah having more free CPU is better. Maybe just printing the progress percentage is better?

For the testing part i know it's faster using config but it's not optimal, maybe i can add some options to run.py, by default it will ask to the user, but if `--anime` or `--film` is specified it will automatically go to that

**Comment by Arrowar** [comment]
With argparse i think that is not that faster but will work, maybe can select by default --film, so there is only need to pass --anime to switch.

**Comment by Arrowar** [comment]
> > Yes I know, but for testing is easier with config but no problem. Maybe tqdm need to be fix, it use to much cpu, but is complicate to find the fix.
> 
> well it's graphically pleasant but (in my case) it will be run on a raspbarry where i host the plex server so yeah having more free CPU is better. Maybe just printing the progress percentage is better?
> 
> For the testing part i know it's faster using config but it's not optimal, maybe i can add some options to run.py, by default it will ask to the user, but if `--anime` or `--film` is specified it will automatically go to that

The main problem is decrypt ts files using iv and key that use all cpu sometimes, and the max workers.

**Comment by FrancescoGrazioso** [comment]
> With argparse i think that is not that faster but will work, maybe can select by default --film, so there is only need to pass --anime to switch.

as i said, as a user experience it's better to have a choice every time, i'm not really into using one or the other by default, keep in mind that if you don't give the choice in docker is gonna be a problem. 

Anyway tests went well, i was able to install and run it on docker in my raspberry pi, i'll add the `argparse` and for me it's done

**Comment by Arrowar** [comment]
Ok perfect.

**Comment by FrancescoGrazioso** [comment]
@Ghost6446 all good by me (also, the discord invitation in expired, it dosen't wotk)

**Comment by Arrowar** [comment]
I know it is available only for 7 day, i select no expire but doesnt work.

**Comment by Arrowar** [comment]
> @Ghost6446 all good by me (also, the discord invitation in expired, it dosen't wotk)

Now work.

**Pull request merged**
