### PR TITLE
fix codec not found causing crash on some movies

### PR DESCRIPTION
**Pull request by FrancescoGrazioso**
Fix for #108

### CODE REVIEW

**Comment by FrancescoGrazioso** [comment]
@Ghost6446 the problem is also present down in the file in this block of code

```
with open(file_list_path, 'w') as file_list:
                for ts_file in ts_files:
                    #absolute_path = os.path.abspath(os.path.join(full_path, ts_file))
                    relative_path = os.path.relpath(os.path.join(full_path, ts_file))
                    file_list.write(f"file '{relative_path}'\n")

            # Concatenate and save the files and return the path to the output filename
            return concatenate_and_save(
                file_list_path=file_list_path,
                output_filename=out_file_name,
                v_codec=self.codec.video_codec_name,
                a_codec=self.codec.audio_codec_name,
                bandwidth=self.codec.bandwidth
            )
```

tomorrow i'll take a look and check if i can prevent it from happening

**Comment by Arrowar** [comment]
Ok, codecs for the moment is not use, but there are always the codecs in a m3u8 playlist.

**Comment by Ghost6446** [comment]
> Ok, codecs for the moment is not use (use too much cpu), but there arw always the codecs in a m3u8 playlist.

**Comment by FrancescoGrazioso** [comment]
@Ghost6446 should be fixed, now the movie is downloaded and joined correctly. Don't really know if it's the final solution, i'll get again to it if the bug come back on other titles

**Comment by Arrowar** [comment]
> @Ghost6446 should be fixed, now the movie is downloaded and joined correctly. Don't really know if it's the final solution, i'll get again to it if the bug come back on other titles

I applied a patch to get the resolution and the codecs in other way.

**Pull request closed without merging**
